# Server Port
server:
  port: 8080

# Spring Datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # !!! 아래 url, username, password를 실제 사용하시는 MySQL 정보로 수정해주세요 !!!
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  # Spring JPA
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티 변경점을 감지하여 DB에 반영
    show-sql: true # JPA가 생성하는 SQL을 로그로 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 포맷팅

  # Spring Session
  session:
    store-type: jdbc # 세션을 데이터베이스에 저장
    jdbc:
      initialize-schema: always # 애플리케이션 시작 시 세션 테이블 자동 생성

  # Thymeleaf
  thymeleaf:
    cache: false # 개발 중에는 타임리프 캐시를 비활성화하여 변경사항 즉시 반영